### ISSUE TITLE
How to listen currentItem

### ISSUE THREAD

**Issue by manuelkern** [eddiemf/vue-scrollactive#10]
Hello,

I have more a question than issue. I would like to listen "currenItem" on the itemchanged function. I just don't know how to pass the element... 

This is more or less what I have in mind: v-on:itemchanged="update(currenItem)"

Sorry for my noobie question.

Thanks

**Comment by manuelkern** [comment]
All good I finally figure it out. I had to pass the argument this way @itemchanged="updateScroll(...arguments)"

Tanks

**Comment by eddiemf** [comment]
Sorry for the delay, I'm glad you figured it out :D 

Best of luck

**Comment by dscummings** [comment]
Hi,

I'm also having trouble with catching the currentItem (my vue & javascript skills are pretty basic). I've got the following nav:

```
<scrollactive class="nav" v-on:itemchanged="activeProject(currentItem)" active-class="active">
    <a v-for="project in projects" v-bind:href="'#' + project.id" class="scrollactive-item">{{project.title}}</a>
</scrollactive>
```

calling this method:
```
activeProject(currentItem) {
    console.log(currentItem);
}
```
..which returns 'undefined'. Any chance you could point out what i'm doing wrong?

Many thanks

**Comment by eddiemf** [comment]
Hello @dscummings! 

I'm sorry about that, but the documentation is wrong in the event listener implementation example. I'll be fixing that really soon!

In order to access the event you should pass only the method name in the listener as so: 
`v-on:itemchanged="activeProject"` 

And your method should look like this:
```
activeProject(event, currentItem, lastActiveItem) {
    console.log(event); // Will log the scroll event
    console.log(currentItem); // Will log the current item
    console.log(lastActiveItem); // Will log the last active item
}
```
