### ISSUE TITLE
Navigation breaks when using scrollactive AND router.

### ISSUE THREAD

**Issue by sandrooco** [eddiemf/vue-scrollactive#12]
Hi guys

I have a page with a few different sections (all of these have a vue-scrollactive linking). When clicking on an item (let's say from `#team`), a detailpage opens (= route navigated, `#/team/sandrooco`).
Then, when clicking on a back button, `this.$router.go(-1);` executes. The problem: Vue will not recognize `#team` as route (because it doesn't exist...) and the user will be lost (no navigation possible).

I hope you understand it, it's quite complicated.

I use vue-scrollactive `0.5.1` and vue `2.5.2`.

**Comment by sandrooco** [comment]
Yup that works! Thanks for the great response time and solution.
Only problem: The scroll position isn't saved in Internet Explorer.

**Comment by eddiemf** [comment]
I'm glad it worked :)

What do you mean by the "the scroll position isn't saved"?

**Comment by sandrooco** [comment]
Sorry, that was quite unclear (updated it).
The problem is, that IE doesn't restore the scroll position when going back to the overview, the user has to scroll down again.

**Comment by eddiemf** [comment]
Oh ok, I'll check that out. Does it occur in all IE versions or only in older ones?

**Comment by sandrooco** [comment]
It happens on IE11, probably on older versions too. I don't think that's a problem of scrollactive, rather simply IE.
I ended up saving the scroll position in a vuex store before going to the other route, then setting the position according to that when going back.
