### ISSUE TITLE
Sections out of the viewport

### ISSUE THREAD

**Issue by eduardocmoreno** [eddiemf/vue-scrollactive#13]
Hi @eddiemf, is there any option to "active" the item in menu only if the trackable sections are really in viewport?

Example: I have 5 sections in sequence, but I'd like to activate menu items only when the scroll reaches the sections 1, 3 and 5. So, if I reach section 2 or 4, no items in menu should be active.

Thanks and congrat for the very nice plugin.

**Comment by eddiemf** [comment]
Hey @eduardocmoreno! I've added an `exact` prop to the plugin which works kinda like a router `exact`, meaning it will match the sections `exact`ly to the items you have inside the plugin if set to `true`, or match to the last active section if set to `false` (default).

You should update your local version of `vue-scrollactive` and add this new prop set to `true` in your project and all should work nicely.

I'll also soon add instructions to the readme.

And thanks for the congrats!
