### ISSUE TITLE
Cannot read property 'offsetHeight' of null

### ISSUE THREAD

**Issue by ackushiw** [eddiemf/vue-scrollactive#15]
When used with lazy loading of components I get this error
`Cannot read property 'offsetHeight' of null`

**Comment by nav16** [comment]
I am having same issue, any solution?

**Comment by eddiemf** [comment]
Hello guys, sorry for the delayed response, I just relocated to another country and was completely off from Github for some time.

It seems to me that for some reason this `const target = document.getElementById(item.hash.substr(1));` is returning `null`, where `item` is one of your `.scrollactive-item`. Does this only happen using lazy loading? Have you tested without using it? I've never used this lazy loading of components before, so it might be the problem, but can be another thing too.

Thanks for the feedback!

**Comment by mariojankovic** [comment]
I had the same issue. One of my ID's was undefined, so I fixed that by renaming my ID's/href's using index instead (`:id="`item-${index}`"` instead of `:id="item.slug"`)
