### ISSUE TITLE
Multiple active class

### ISSUE THREAD

**Issue by Geminii** [eddiemf/vue-scrollactive#20]
Hi ! 
Thanks for your project. I use it for my work but i found a problem about the active class navigation. 

To reproduce it : 
`
<scrollactive id="nav-items" class="my-nav" active-class="active" v-on:itemchanged="onItemChanged"
                              :offset="90"
                              :duration="500"
                              :modify-url="false">
                </scrollactive>
`

My navigation looks like : 
`<nav class="scrollactive-nav my-nav" id="nav-items"><a href="#introduction" class="scrollactive-item">Introduction</a><a href="#factsDemandsProcedure" class="scrollactive-item">factsDemandsProcedure</a><a href="#motifs" class="scrollactive-item">motifs</a><a href="#dispositif" class="scrollactive-item">dispositif</a><a href="#signature" class="scrollactive-item active">signature</a></nav>`

Each sections have the following template : 
`<section id="introduction" class="part"><p>My content ...</p></section>`

Each section has different height. And it's the problem because `dispositif` and `signature` section have a little height and place at the end of the document.

**Case reproduction :** 
- click on the last item `signature` 
   => scroll to the end of the page
   => active the class 
- scroll up 
   => last item `signature` have always active class 
   => item `motifs` has active class  

I bind the `itemchanged` methods to debug then i noticed something. My console.log not appears when i click on the last section probably because the last section can not be reached by the window's offset. 

Thanks for your answer.

**Comment by eddiemf** [comment]
Oh, that's interesting, but I remember this "working" properly some time ago, only it would not highlight sections it can't reach, but I'll try to reproduce and see if I can find something.

Thanks for the feedback :)

**Comment by Geminii** [comment]
@eddiemf Do you reproduce the problem ? 

Regards,

**Comment by Geminii** [comment]
Hi @eddiemf, 
Do you fix this bug ? 

Thanks for your answer ;)

**Comment by eddiemf** [comment]
Hey there, sorry for the long waiting time, I didn't have a lot of time to maintain my libraries, but this is finally fixed and will be implemented in the next release very soon :)
