### ISSUE TITLE
element.hash caught urlencode

### ISSUE THREAD

**Issue by shalldie** [eddiemf/vue-scrollactive#24]
At: https://github.com/eddiemf/vue-scrollactive/blob/master/src/scrollactive.vue#L196

```js
const target = document.getElementById(item.hash.substr(1));
```

item.hash may urlencode the href attribute, so when i use it with some unicode word like this:

```html
<scrollactive class="my-nav">
  <a href="#home-家" class="scrollactive-item">Home</a>
  ...
</scrollactive>
```

it may urlencode it, try to find the element with a id `home-%E5%AE%B6`  >_<#@!

**Comment by shalldie** [comment]
I can make a pr if u are busy. 😆😆
Wait for your response.

**Comment by eddiemf** [comment]
Hello, sorry for the delay and thanks for the feedback. I just fixed this issue and will add it to the next release very soon :)
