### ISSUE TITLE
modifyUrl setting not useful

### ISSUE THREAD

**Issue by gjycdd** [eddiemf/vue-scrollactive#25]
show my code
```
<scrollactive
      :modify-url="false"
      :always-track="true"
      :duration="800"
      bezier-easing-value=".5,0,.35,1"
>
      <h-navbar
              :slider="{
                width: 50,
                height: 4,
                color: '#FF4A83',
              }"
              :tabs="tabs"
      >
              <a :slot="`tab${index}`" :href="`#floor${index + 1}`" v-for="(item, index) in tabs" :key="index">{{item}}</a>
      </h-navbar>
</scrollactive>
```
as i set props modifyUrl to false
but i find noting happend
the url is also be modifyed,
like: `http://localhost:8080/#/course/courseList?courseId=COURSEID` to `http://localhost:8080/#/floor1`
i do something error?

**Comment by gjycdd** [comment]
ou, 
i see it,
 if i set `class='scrollactive-item'` , 
modifyUrl is useful, 
but there is also question,
i cant scroll to dom

**Comment by eddiemf** [comment]
Hello, do you still have the described problem? I couldn't reproduce it in my environment, but might be because you're using router with hash mode instead of history mode.

I would be glad if you or someone could reproduce this and tell if it's a bug or just something else.

**Comment by eddiemf** [comment]
Great to know then :) Cheers
