### ISSUE TITLE
vue-scrollactive do not work in Firefox and IE11

### ISSUE THREAD

**Issue by VitalyBesk** [eddiemf/vue-scrollactive#3]
vue-scrollactive do not work in Firefox 55 (Mac OS Sierra, Windows10 ) and IE11.

In Chrome, Safari, Edge it works perfectly.

**Comment by FrancoisH** [comment]
My commit should fix your issue.

Just update your component and add `event` variable to the `onScroll` method like this: `onScroll(event)` and recompile your assets.

**Comment by eddiemf** [comment]
Thanks for the help guys! I'll update it tonight :)
