### ISSUE TITLE
Package not working if scrollContainer is not provided

### ISSUE THREAD

**Issue by matkovsky** [eddiemf/vue-scrollactive#30]
Hi!

Since the latest release the plugin stopped working if there is no `scrollContainer` provided. The issue is here:
https://github.com/eddiemf/vue-scrollactive/commit/06dfcb371c1318c6a0aed42546918ac11449629f#diff-4959140d7c2bf6ca765de6d9c393a83cR363

Since `this.scrollContainer` is always set _(it's a computed property, and it's either the one set in props, otherwise `window`)_, we try to get the `offsetTop` of `window`. Since `window` does not have such property, it returns `undefined`. Some number (`yPosition`) minus `undefined` is `NaN`. So our script breaks.

Because there might be a few other elements without `offsetTop` properties, I would not suggest checking for whether the container is `window` or not, rather check for the availability of `offsetTop`.

Something like this would probably work fine:

```js
if (this.scrollContainer && typeof this.scrollContainer.offsetTop === 'number') {
  return yPosition - this.scrollContainer.offsetTop;
}
```

**Comment by eddiemf** [comment]
Oh man, what a silly mistake, thanks for pointing that out @matkovsky, I'll fix it and release a patch as soon as possible :)
