### ISSUE TITLE
Problem Unknown custom element: <scrollactive> when trying to use the component

### ISSUE THREAD

**Issue by krrskl** [eddiemf/vue-scrollactive#45]
Hello, after doing the installation of the package using npm, and configure it as explained in the documentation. I try to use it and it throws me this error:

> vue.esm.js?efeb:610 [Vue warn]: Unknown custom element: <scrollactive> - did you register the component correctly? For recursive components, make sure to provide the "name" option. found in
---> <Home> at src/views/Home.vue
       <App> at src/App.vue
         <Root>

**Comment by aghayeff** [comment]
At main.js instead of using 
`var VueScrollactive = require('vue-scrollactive');`

use
`import VueScrollactive from 'vue-scrollactive'`

**Comment by krrskl** [comment]
Excellent! this has worked.
