### ISSUE TITLE
Is it possible to trigger on elements on bottom of page?

### ISSUE THREAD

**Issue by StefKors** [eddiemf/vue-scrollactive#48]
If I have a section that isn't the full page height, is it still possible to trigger vue-scrollactive when it's in view?

(btw if there is a better location to ask these questions let me know)

**Comment by eddiemf** [comment]
Yeah sure, it should be definitely possible. The class is applied based on wether the top of screen + offset value reached the position of the section you defined. The only problem you might have is in case it's the last section and it's too small for the top of screen to reach it, so it will never have the active class.

**Comment by StefKors** [comment]
Yeah, I was thinking probably giving it 80vh or some would work. Is it possible to mod it so instead of X from top it triggers on when element is in frame?

Another option would be to perhaps manually trigger scrollactive? Is that possible

**Comment by atiar-cse** [comment]
It's not triggering on bottom of page small section in height about 200px. How we can resolve it?

**Comment by MaartenVenema** [comment]
This issue still persists. When you scroll down but the last section is not close enough to the top of the viewport the active-state for the last section will not get triggered.

**Comment by vladninja** [comment]
Any progress?
