### ISSUE TITLE
Problem with entering hashed adresses

### ISSUE THREAD

**Issue by q-23** [eddiemf/vue-scrollactive#50]
My problem is that when I enter anchored position on page, eg. /#contact, it always renders at the top, not in the given position, when I disable scrollactive the problem ends.

**Comment by DamianMullins** [comment]
I had this issue too in one of my projects. I've had to add some code which performs the scrolling correctly after page load. Is there any way we could make the `scrollToHashElement` function call optional in the `mounted` hook? I am happy to put a pull request together for this.

**Comment by DamianMullins** [comment]
I've just noticed that #54 covers this.

**Comment by tomparle** [comment]
> I've just noticed that #54 covers this.

Indeed, I do not know when this request will be accepted but feel free to use my branch if you need this feature !

**Comment by eddiemf** [comment]
Fixed by #54
