### ISSUE TITLE
Follow Vue component naming convention

### ISSUE THREAD

**Issue by CasperEngl** [eddiemf/vue-scrollactive#53]
https://vuejs.org/v2/style-guide/#Priority-A-Rules-Essential-Error-Prevention

### Current usage
```
<scrollactive></scrollactive>
```

### Export the component so it will be used with a hyphen
```
<scroll-active></scroll-active>
```

### Issue
Some editors (Such as VSCode) will see this as an invalid element. If the component follows the naming convention of having a hyphen, it will just be seen as a custom element ready to be picked up by some javascript.

Specifically with my editor, I had a problem with two nav elements being rendered. Turns out, I had forgotten to put a slash in the end tag, resolving in the next element being included in a secondary nav tag like so:
```
<scrollactive>
    <a href="...">...</a>
    <a href="...">...</a>
    <a href="...">...</a>
<scrollactive>
    
<a href="...">...</a>
```
Result:
```
<nav class="scrollactive-nav">
    <a href="..." class="scrollactive-item">...</a>
    <a href="..." class="scrollactive-item">...</a>
    <a href="..." class="scrollactive-item">...</a>
    <a href="..." class="scrollactive-item">...</a>
    <a href="..." class="scrollactive-item">...</a>
    <nav class="scrollactive-nav">
        <a href="..." class="none-scroll-item">...</a>
    </nav>
</nav>
```

Edit: Added link to style guide documentation

**Comment by eddiemf** [comment]
Sounds reasonable. Definitely not worth it to change the API now but I'll certainly make this change when v1.0 is ready to be released with some breaking changes. Thanks!
