### ISSUE TITLE
scrollactive inside other scrollactive

### ISSUE THREAD

**Issue by Excelsiorer** [eddiemf/vue-scrollactive#59]
Hello! I need menu like this:
https://excelsiorer.github.io/portfolio/instalations.html

This i make on vanila js. Now i try make it on vue, and use this library.

I use this markdown:
`    <scrollactive active-class="menu--active" tag="ul">
        <li>
            <a href="#project-1" class="scrollactive-item"> Project 1 </a>
            <scrollactive active-class="submenu--active" tag="ul">
                <li>
                    <a href="#submenu-1-1" class="scrollactive-item"> Submenu 1-1 </a>
                </li>
                <li>
                    <a href="#submenu-1-2" class="scrollactive-item"> Submenu 1-2 </a>
                </li>
                <li>
                    <a href="#submenu-1-3" class="scrollactive-item"> Submenu 1-3 </a>
                </li>
                <li>
                    <a href="#submenu-1-4" class="scrollactive-item"> Submenu 1-4 </a>
                </li>
            </scrollactive>
        </li>

        <li>
            <a href="#project-2" class="scrollactive-item"> Project 2 </a>
            <scrollactive active-class="submenu--active" tag="ul">
                <li>
                    <a href="#submenu-2-1" class="scrollactive-item"> Submenu 2-1 </a>
                </li>
                <li>
                    <a href="#submenu-2-2" class="scrollactive-item"> Submenu 2-2 </a>
                </li>
                <li>
                    <a href="#submenu-2-3" class="scrollactive-item"> Submenu 2-3 </a>
                </li>
                <li>
                    <a href="#submenu-2-4" class="scrollactive-item"> Submenu 2-4 </a>
                </li>
            </scrollactive>
        </li>
    </scrollactive>`

but both classes add only on second scrollactive tag.
How i can change it?

**Comment by fmcdigital** [comment]
I need that too.

**Comment by eddiemf** [comment]
I'm not sure if it's possible to do it the way you're trying but you can achieve that behaviour by simply listening for the `itemchanged` event and whenever it triggers you find the parent `<li>` and add the class to it.

- have only the sub menus have the `.scrollactive-item` class
- `itemchanged` triggered
- remove active class from all parent `<li>`s
- find the current item parent `<li>`
- add the active class to it

Something like that should work for now.

I'm thinking about implementing something like that but the way it currently works right now it's impossible and would require a full rework and possibly performance issues so I'm still studying the possibility.

**Comment by fmcdigital** [comment]
Yes, I'm doing this right now

**Comment by eddiemf** [comment]
I'll close this since I'll not be implementing this behaviour anytime soon an also there's a workaround to deal with it. Let me know if you need any further help :)
