### ISSUE TITLE
It won't scroll when I add section

### ISSUE THREAD

**Issue by christianemmanuel** [eddiemf/vue-scrollactive#66]
I already add section for every link. but it doesn't work.

**Comment by eddiemf** [comment]
The plugin works as you can see in the demo, so you're probably doing something wrong which I can't help without any piece of your code 😅

**Comment by christianemmanuel** [comment]
Hi It's working now on my end, the problem is when I put overflow-x: hidden in body. It won't work.  thanks by the way.
