### ISSUE TITLE
this.scrollContainerSelector is undefined 

### ISSUE THREAD

**Issue by ctwowt** [eddiemf/vue-scrollactive#67]
https://github.com/eddiemf/vue-scrollactive/blob/80046ac552f006b789787ef99625819e85097c44/src/ScrollContainer.js#L6

container is always window 

```js
 container = document.querySelector(containerSelector);
 container = document.querySelector(this.scrollContainerSelector);
```

**Comment by eddiemf** [comment]
Thanks for that! Refactoring mistakes, it's fixed in `v0.9.3` now :)
