### ISSUE TITLE
Scrollspy doesn't work on iPhone?

### ISSUE THREAD

**Issue by iamdubx** [eddiemf/vue-scrollactive#8]
Hello. I noticed that scrollspy functional doesn't work on iOS. Is this wanted behavior?

**Comment by eddiemf** [comment]
I'm not sure about it, I don't use iOS, but I'll make some tests this monday to see if I catch something, thanks for the feedback!

**Comment by iamdubx** [comment]
@eddiemf hey, mate, I found what cause the issue. `forEach` doesn't work with nodeList on iOS - https://toddmotto.com/ditch-the-array-foreach-call-nodelist-hack/

**Comment by iamdubx** [comment]
@eddiemf I've tested it on iPhone 6S iOS 9. Doesn't work both in Chrome and Safari. I had the similiar truble with my own scrollspy script, and also had forEach in it. After I change it to `Array.prototype.forEach.call` it begin to work! But it's better to make own `forEach` function, like in that article.

**Comment by eddiemf** [comment]
Great, I'll patch it this weekend and it should probably work then :)

**Comment by iamdubx** [comment]
@eddiemf awesome! Will looking forward.

**Comment by eddiemf** [comment]
Thanks for the tip, but my free trial was already used hehe

I updated the plugin, it should work as intended now, let me know if anything is still out of place.

**Comment by iamdubx** [comment]
@eddiemf everything looks good! Thanks for update, mate!
