### ISSUE TITLE
TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by kartikbhargav11** [eddiemf/vue-scrollactive#83]
In Nuxt.js it gives TypeError: Cannot read property 'substr' of undefined on render

**Comment by rylax** [comment]
Can you share what the solution to your problem was? Facing the exact same issue.

**Comment by rudashi** [comment]
@rylax 
Be sure you used class **scrollactive-item** on **a** tag.
If you put that class on other child element like **li** it will fail.

```html
<scrollactive class="my-nav" tag="ul">
   <li>
      <a href="#home" class="scrollactive-item">Home</a>
  </li>
</scrollactive>
```
